apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: deploy-pipeline
  name: deploy-pipeline
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'ssh://git@inhousegiturl.com/repo/project.git'
    sourceSecret:
      name: openshift-source-builder
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  triggers: []
